LEETCODE=1 539 884 179 241 214 386 2707 3043 2416 729 731 641 432 1381 1497 1331 1590 2491 567 1813 2696 921 962 9 1942 2406 2938 1405 670 2044 1545 1106 1593 951 1233 1277 2684
NOV2024=1957 2490 796 3163 2914 3011 3133 3097 2601 2070 2563 2064 3254 1652 2461 1861
LEETCODE_COMPILER_SETTING= -O2 -fsanitize=address
# ASAN_OPTIONS=detect_leaks=1
BIN=./bin

all: $(LEETCODE)

1: 1_two_sum.cpp
	clang++ -o $(BIN)/$@ $<

539: 539_minimum_time_difference.cpp
	clang++ -o $(BIN)/$@ $<

884: 884_uncommon_words_from_two_sentences.cpp
	clang++ -o $(BIN)/$@ $<

179: 179_largest_number.cpp
	clang++ -o $(BIN)/$@ $<
	@$(BIN)/$@

241: 241_different_ways_to_add_parentheses.cpp
	clang++ -o $(BIN)/$@ $<
	@$(BIN)/$@

214: 214_shortest_palindrome.cpp
	clang++ -o $(BIN)/$@ $< -g
	# @$(BIN)/$@

386: 386_lexicographical_numbers.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

2707: 2707_extra_characters_in_a_string.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

3043: 3043_find_the_length_of_the_longest_common_prefix.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

2416: 2416_sum_of_prefix_scores_of_strings.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

729: 729_my_calendar_I.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

731: 731_my_calendar_II.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

641: 641_design_circular_deque.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

432: 432_allone_data_structure.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

1381: 1381_design_a_stack_with_increment_operation.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1497: 1497_check_if_array_pairs_are_divisible_by_k.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1331: 1331_rank_transform_of_an_array.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1590: 1590_make_sum_divisible_by_p.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2491: 2491_divide_players_into_teams_of_equal_skill.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

567: 567_permutation_in_string.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

1813: 1813_sentence_similarity_iii.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2696: 2696_minimum_string_length_after_removing_substrings.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

921 : 921_minimum_add_to_make_parentheses_valid.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

962 : 962_maximum_width_ramp.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

9 : 9_palindrome_number.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1942 : 1942_the_number_of_the_smallest_unoccupied_chair.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2406 : 2406_divide_intervals_into_minimum_number_of_groups.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

2530: 2530_maximal_score_after_applying_k_operations.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2938: 2938_separate_black_and_white_balls.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1405: 1405_longest_happy_string.cpp
	clang++ -o $(BIN)/$@ $< -g # $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

670: 670_maximum_swap.cpp
	clang++ -o $(BIN)/$@ $< -g # $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2044: 2044_count_number_of_maximum_bitwise_or_subsets.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1545: 1545_find_kth_bit_in_nth_binary_string.cpp
	clang++ -o $(BIN)/$@ $< -g # $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1106: 1106_parsing_a_boolean_expression.cpp
	clang++ -o $(BIN)/$@ $< -g # $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1593: 1593_split_a_string_into_the_max_number_of_unique_substrings.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

951: 951_flip_equivalent_binary_tree.cpp
	clang++ -o $(BIN)/$@ $< -std=c++20
	@echo "Doesn't has TreeNode implementation so nothing to run"

1233: 1233_remove_subfolders_from_the_filesystem.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1277: 1277_count_square_submatrices_with_all_ones.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2684: 2684_maximum_number_of_moves_in_a_grid.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1957: 1957_delete_characters_to_make_fancy_string.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2490: 2490_circular_sentence.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

796: 796_rotate_string.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

3163: 3163_string_compression_iii.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2914: 2914_minimum_number_of_changes_to_make_binary_string_beautiful.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

3011: 3011_find_if_array_can_be_sorted.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

3133: 3133_minimum_array_end.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

3097: 3097_shortest_subarray_with_or_at_least_k_ii.cpp
	clang++ -o $(BIN)/$@ $< -g # $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2601: 2601_prime_subtraction_operation.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2070: 2070_most_beautiful_item_for_each_query.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2563: 2563_count_the_number_of_fair_pairs.cpp
	clang++ -o $(BIN)/$@ $< -g # $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2064: 2064_minimized_maximum_of_products_distributed_to_any_store.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

3254: 3254_find_the_power_of_k-size_subarrays_i.cpp
	clang++ -o $(BIN)/$@ $< -g # $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1652: 1652_defuse_the_bomb.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

2461: 2461_maximum_sum_of_distinct_subarrays_with_length_k.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING)
	@$(BIN)/$@

1861: 1861_rotating_the_box.cpp
	clang++ -o $(BIN)/$@ $< -g $(LEETCODE_COMPILER_SETTING) -Wno-braced-scalar-init
	@$(BIN)/$@
