LEETCODE=1 539 884 179
BIN=./bin

all: $(LEETCODE)

1: 1_two_sum.cpp
	clang++ -o $(BIN)/$@ $<

539: 539_minimum_time_difference.cpp
	clang++ -o $(BIN)/$@ $<

884: 884_uncommon_words_from_two_sentences.cpp
	clang++ -o $(BIN)/$@ $<

179: 179_largest_number.cpp
	clang++ -o $(BIN)/$@ $<
	@$(BIN)/$@

241: 241_different_ways_to_add_parentheses.cpp
	clang++ -o $(BIN)/$@ $<
	@$(BIN)/$@

214: 214_shortest_palindrome.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@

386: 386_lexicographical_numbers.cpp
	clang++ -o $(BIN)/$@ $< -g
	@$(BIN)/$@
